service: slack-vegeta

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 3008
  timeout: 600
  region: ap-northeast-1

  environment:
    SLACK_TOKEN: ""

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  slash:
    handler: bin/slack
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - Queue
              - Arn

resources:
  Resources:
    Queue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "vegeta-queue"
